"""Remove title from company_info

Revision ID: 51adef6b8592
Revises: 
Create Date: 2025-05-21 13:05:11.044104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51adef6b8592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
